name: kasir_warjo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.6
  intl: ^0.18.1
  introduction_screen: ^3.1.12
  lottie: ^2.7.0
  syncfusion_flutter_charts: ^23.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/warjo.png
    - lib/assets/lotties/Login.json
